# backend/Dockerfile.backend

# Usamos una imagen de Node optimizada
FROM node:18-alpine
WORKDIR /app

# Copiamos solo los archivos de dependencias primero para aprovechar el cache de Docker
COPY package.json pnpm-lock.yaml* ./

# Instalamos las dependencias
RUN npm install --production

# Copiamos el resto del código del backend
COPY . .

# Exponemos el puerto en el que corre el servidor Express
EXPOSE 3000

# Comando para iniciar el servidor
CMD [ "node", "server.js" ]
